services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./config/browser.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid-net"]
    networks:
      - selenoid-net

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprint9_tests
    depends_on:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444/wd/hub
    volumes:
      - ./allure-results:/Sprint_9/allure-results
    networks:
      - selenoid-net
      
networks:
  selenoid-net:
    name: selenoid-net
    driver: bridge
    