name: Sprint 9 Tests CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code  
        uses: actions/checkout@v4
      - name: Run tests with docker-compose
        run: docker-compose up --build --exit-code-from tests
